adoptionsite/models.py
from adoptionsite import db

class Puppies(db.Model):
    __tablename__ = "puppies"

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.Text)
    owner=db.relationship('Owner',backref='puppies',uselist=False)


    def __init__(self,name):
        self.name = name


    def __repr__(self):
        if self.owner:
            return f"the puppy name is {self.name} and owner is {self.owner.name}"
        else:
            return f" puppy name:{self.name} has no owner assigned "



class Owner(db.Model):
    __tablename__="owner"


    id=db.Column(db.Integer,primary_key=True)
    pup_id=db.Column(db.Integer,db.ForeignKey("puppies.id"))
    name=db.Column(db.Text)

    def __init__(self,name,pup_id):

        self.name = name
        self.pup_id=pup_id



    def __repr__(self):
        return f"the owner is {self.name}"

adoptionsite/owner/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,SubmitField,IntegerField

class AddForm(FlaskForm):
    id=IntegerField("enter puppy id")
    name =StringField("enter your name")
    submit=SubmitField('submit')

adoptionsite/puppies/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,SubmitField,IntegerField

class AddForm(FlaskForm):
    name = StringField('name of puppy')
    submit= SubmitField('submit')


class DelForm(FlaskForm):
    id = IntegerField('enter id')
    name=StringField("enter name")
    submit= SubmitField('submit')

adoptionsite/__init__.py
import os
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate

app = Flask(__name__)

app.config['SECRET_KEY'] = 'vaza'

basedir = os.path.abspath(os.path.dirname(__file__))
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///' + os.path.join(basedir, 'data.sqlite')
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False


db = SQLAlchemy(app)
Migrate(app, db)

from adoptionsite.owner.view import owners_blueprint
from adoptionsite.puppies.views import puppies_blueprint

app.register_blueprint(owners_blueprint, url_prefix='/owners')
app.register_blueprint(puppies_blueprint, url_prefix='/puppies')

adoptionsite/puppies/views.py
from flask import Flask, url_for, render_template, redirect, Blueprint
from adoptionsite import db
from adoptionsite.models import Puppies
from adoptionsite.models import Owner
from adoptionsite.puppies.forms import AddForm, DelForm

puppies_blueprint = Blueprint(
    'puppy', __name__, template_folder='templates/puppies',static_folder='static')


@puppies_blueprint.route('/add', methods=["GET", "POST"])
def add():
    form = AddForm()

    if form.validate_on_submit():
        name = form.name.data
        new = Puppies(name)
        db.session.add(new)
        db.session.commit()
        return redirect(url_for('puppy.list_pup'))

    return render_template('add.html', form=form)


@puppies_blueprint.route('/list', methods=["GET", "POST"])
def list_pup():
    pups = Puppies.query.all()
    owns = Owner.query.all()

    return render_template('list.html', pups=pups,owns=owns)


@puppies_blueprint.route('/delete', methods=["GET", "POST"])
def remove_pup():
    form = DelForm()

    if form.validate_on_submit():
        id = form.id.data
        pup = Puppies.query.get(id)
        db.session.delete(pup)
        db.session.commit()
        return redirect(url_for("puppy.list_pup"))

    return render_template("delete.html", form=form)

adoptionsite/templates/add.html
{%extends "index.html"  %}

{% block content%}

<section class="bg-secondary text-body p-5">
  <div class="container">
    <h1>Do you want to give away your dog?</h1>
    <h3>add a new puppy to our collection </h3>

    <form method="post">
      {{form.hidden_tag()}}
      {{form.name.label}} {{form.name}}
      {{form.submit}}

    </form>

  </div>

</section>



{% endblock %}

adoptionsite/templates/delete.html
{% extends "index.html" %}

{% block content%}
<section class="bg-secondary text-body p-5">
  <div class="container">
    <h1>Dp you want to Adopt a puppy?</h1>
    <h3>if so pls choose the name and enter id of that puppy</h3>



    <form  method="post">


        {{form.hidden_tag()}}
        {{form.id.label}} {{form.id}}


        {{form.name.label}} {{form.name}}
        {{form.submit}}



    </form>

  </div>

</section>



{% endblock %}

adoptionsite/templates/index.html
<html>
	<head>
		<title>Dopetrope by HTML5 UP</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="assets/css/main.css" />
	</head>
	<body class="homepage is-preload">
		<div id="page-wrapper">

			<!-- Header -->
				<section id="header">

					<!-- Logo -->
						<h1><a href="index.html">FIND HUMANS</a></h1>

					<!-- Nav -->
						<nav id="nav">
							<ul>
								<li class="current"><a href="{{url_for('index')}}">Home</a></li>
                <li><a href="{{url_for('puppy.add')}}">Right Sidebar</a></li>
                <li><a href="{{url_for('puppy.remove_pup')}}">Right Sidebar</a></li>


								<li><a href="{{url_for('puppy.list_pup')}}">Right Sidebar</a></li>
								<li><a href="{{url_for('owner.add')}}">No Sidebar</a></li>
							</ul>
						</nav>
{% block content %}
            <!-- CUT -->

					<!-- Banner -->
						<section id="banner">
							<header>
								<h2>THIS IS AN ADOPTION SITE</h2>
								<p>BY SAHAL M</p>
							</header>
						</section>

					<!-- Intro -->
						<section id="intro" class="container">
							<div class="row">
								<div class="col-4 col-12-medium">
									<section class="first">
										<i class="icon solid featured fa-cog"></i>
										<header>
											<h2>Ipsum consequat</h2>
										</header>
										<p>Nisl amet dolor sit ipsum veroeros sed blandit consequat veroeros et magna tempus.</p>
									</section>
								</div>
								<div class="col-4 col-12-medium">
									<section class="middle">
										<i class="icon solid featured alt fa-bolt"></i>
										<header>
											<h2>Magna etiam dolor</h2>
										</header>
										<p>Nisl amet dolor sit ipsum veroeros sed blandit consequat veroeros et magna tempus.</p>
									</section>
								</div>
								<div class="col-4 col-12-medium">
									<section class="last">
										<i class="icon solid featured alt2 fa-star"></i>
										<header>
											<h2>Tempus adipiscing</h2>
										</header>
										<p>Nisl amet dolor sit ipsum veroeros sed blandit consequat veroeros et magna tempus.</p>
									</section>
								</div>
							</div>
							<footer>
								<ul class="actions">
									<li><a href="#" class="button large">Get Started</a></li>
									<li><a href="#" class="button alt large">Learn More</a></li>
								</ul>
							</footer>
						</section>

				</section>
{% endblock %}











        <!-- Footer -->
          <section id="footer">
            <div class="container">
              <div class="row">
                <div class="col-8 col-12-medium">
                  <section>
                    <header>
                      <h2>Blandit nisl adipiscing</h2>
                    </header>
                    <ul class="dates">
                      <li>
                        <span class="date">Jan <strong>27</strong></span>
                        <h3><a href="#">Lorem dolor sit amet veroeros</a></h3>
                        <p>Ipsum dolor sit amet veroeros consequat blandit ipsum phasellus lorem consequat etiam.</p>
                      </li>
                      <li>
                        <span class="date">Jan <strong>23</strong></span>
                        <h3><a href="#">Ipsum sed blandit nisl consequat</a></h3>
                        <p>Blandit phasellus lorem ipsum dolor tempor sapien tortor hendrerit adipiscing feugiat lorem.</p>
                      </li>
                      <li>
                        <span class="date">Jan <strong>15</strong></span>
                        <h3><a href="#">Magna tempus lorem feugiat</a></h3>
                        <p>Dolore consequat sed phasellus lorem sed etiam nullam dolor etiam sed amet sit consequat.</p>
                      </li>
                      <li>
                        <span class="date">Jan <strong>12</strong></span>
                        <h3><a href="#">Dolore tempus ipsum feugiat nulla</a></h3>
                        <p>Feugiat lorem dolor sed nullam tempus lorem ipsum dolor sit amet nullam consequat.</p>
                      </li>
                      <li>
                        <span class="date">Jan <strong>10</strong></span>
                        <h3><a href="#">Blandit tempus aliquam?</a></h3>
                        <p>Feugiat sed tempus blandit tempus adipiscing nisl lorem ipsum dolor sit amet dolore.</p>
                      </li>
                    </ul>
                  </section>
                </div>
                <div class="col-4 col-12-medium">
                  <section>
                    <header>
                      <h2>What's this all about?</h2>
                    </header>
                    <a href="#" class="image featured"><img src="images/pic10.jpg" alt="" /></a>
                    <p>
                      This is <strong>Dopetrope</strong> a free, fully responsive HTML5 site template by
                      <a href="http://twitter.com/ajlkn">AJ</a> for <a href="http://html5up.net/">HTML5 UP</a> It's released for free under
                      the <a href="http://html5up.net/license/">Creative Commons Attribution</a> license so feel free to use it for any personal or commercial project &ndash; just don't forget to credit us!
                    </p>
                    <footer>
                      <ul class="actions">
                        <li><a href="#" class="button">Find out more</a></li>
                      </ul>
                    </footer>
                  </section>
                </div>
                <div class="col-4 col-6-medium col-12-small">
                  <section>
                    <header>
                      <h2>Tempus consequat</h2>
                    </header>
                    <ul class="divided">
                      <li><a href="#">Lorem ipsum dolor sit amet sit veroeros</a></li>
                      <li><a href="#">Sed et blandit consequat sed tlorem blandit</a></li>
                      <li><a href="#">Adipiscing feugiat phasellus sed tempus</a></li>
                      <li><a href="#">Hendrerit tortor vitae mattis tempor sapien</a></li>
                      <li><a href="#">Sem feugiat sapien id suscipit magna felis nec</a></li>
                      <li><a href="#">Elit class aptent taciti sociosqu ad litora</a></li>
                    </ul>
                  </section>
                </div>
                <div class="col-4 col-6-medium col-12-small">
                  <section>
                    <header>
                      <h2>Ipsum et phasellus</h2>
                    </header>
                    <ul class="divided">
                      <li><a href="#">Lorem ipsum dolor sit amet sit veroeros</a></li>
                      <li><a href="#">Sed et blandit consequat sed tlorem blandit</a></li>
                      <li><a href="#">Adipiscing feugiat phasellus sed tempus</a></li>
                      <li><a href="#">Hendrerit tortor vitae mattis tempor sapien</a></li>
                      <li><a href="#">Sem feugiat sapien id suscipit magna felis nec</a></li>
                      <li><a href="#">Elit class aptent taciti sociosqu ad litora</a></li>
                    </ul>
                  </section>
                </div>
                <div class="col-4 col-12-medium">
                  <section>
                    <header>
                      <h2>Vitae tempor lorem</h2>
                    </header>
                    <ul class="social">
                      <li><a class="icon brands fa-facebook-f" href="#"><span class="label">Facebook</span></a></li>
                      <li><a class="icon brands fa-twitter" href="#"><span class="label">Twitter</span></a></li>
                      <li><a class="icon brands fa-dribbble" href="#"><span class="label">Dribbble</span></a></li>
                      <li><a class="icon brands fa-tumblr" href="#"><span class="label">Tumblr</span></a></li>
                      <li><a class="icon brands fa-linkedin-in" href="#"><span class="label">LinkedIn</span></a></li>
                    </ul>
                    <ul class="contact">
                      <li>
                        <h3>Address</h3>
                        <p>
                          Untitled Incorporated<br />
                          1234 Somewhere Road Suite<br />
                          Nashville, TN 00000-0000
                        </p>
                      </li>
                      <li>
                        <h3>Mail</h3>
                        <p><a href="#">someone@untitled.tld</a></p>
                      </li>
                      <li>
                        <h3>Phone</h3>
                        <p>(800) 000-0000</p>
                      </li>
                    </ul>
                  </section>
                </div>
                <div class="col-12">

                  <!-- Copyright -->
                    <div id="copyright">
                      <ul class="links">
                        <li>&copy; Untitled. All rights reserved.</li><li>Design: <a href="http://html5up.net">HTML5 UP</a></li>
                      </ul>
                    </div>

                </div>
              </div>
            </div>
          </section>

      </div>

      <!-- Scripts -->
        <script src="assets/js/jquery.min.js"></script>
        <script src="assets/js/jquery.dropotron.min.js"></script>
        <script src="assets/js/browser.min.js"></script>
        <script src="assets/js/breakpoints.min.js"></script>
        <script src="assets/js/util.js"></script>
        <script src="assets/js/main.js"></script>

    </body>
  </html>

adoptionsite/templates/index4.html
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
  <meta charset="utf-8">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <title>adoption site </title>
</head>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="{{url_for('index')}}">Home</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="{{url_for('puppy.add')}}">Give a puppy </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{url_for('puppy.remove_pup')}}">Adopt a puppy</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{url_for('puppy.list_pup')}}">List of puppies</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{url_for('owner.add')}}">add owner</a>
        </li>

      </ul>
    </div>
  </div>
</nav>

{% block content %}




<section class="bg-secondary text-body p-5">
  <div class="container">
    <h1> WELCOME TO ADOPTION PAGE</h1>
    <p class="lead"> Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
      consequat. Duis aute
      irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

  </div>

</section>

{% endblock %}



<body>

</body>

</html>

adoptionsite/templates/list.html
{% extends "index.html" %}


{% block content %}


<section >

  <div >

    <ul>
      {%for dog in pups%}
      <li>
        {{dog}}
      </li>
      {% endfor %}
    </ul>





  </div>


  <div >

    <h1>owner list</h1>

        <ul>
          {%for i in owns%}
          <li>
            {{i}}
          </li>
          {% endfor %}
        </ul>


  </div>

</section>



{% endblock %}

adoptionsite/templates/owner.html
{%extends "index.html"%}

{%block content%}


<section class="bg-secondary p-5 text-body">

  <div class="container">
    <form method="post">

          {{form.hidden_tag()}}

          {{form.name.label}} {{form.name}}
          {{form.id.label}} {{form.id}}
          {{form.submit}}

    </form>


  </div>

</section>






{% endblock %}